# .cnb.yml
"**":
  push:
    - imports:
        - https://cnb.cool/rss1102.cnb/rss1102-secret/-/blob/main/blog.yml
      services:
        - docker
      stages:
        # cnb 同步代码到 github 仓库 https://cnb.cool/cnb/plugins/tencentcom/git-sync#%E4%BB%8E-cnb-%E5%90%8C%E6%AD%A5%E5%88%B0-github
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/vegetables-school/blog-backend-go.git
            auth_type: https
            username: RSS1102
            password: ${GITHUB_ALL_BLOG_SYNC_TOKEN}
            branch: dev
            insecure_skip_verify: true
            timeout: 300

        # 同名镜像构建&推送 https://docs.cnb.cool/zh/artifact/docker.html#deng-lu-cnb-docker-zhi-pin-ku
        - name: docker login
          script: docker login docker.cnb.cool -u cnb -p ${CNB_TOKEN}
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:dev