version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # env_file:
    #   - /home/env/.env.blog-backend-go.dev
    ports:
      - "8080:8080"
    volumes:
      - blog-backend-go-dev:/blog-backend-go-dev

volumes:
  blog-backend-go-dev:
    external: true