
version: '3.8'

services:
  app: # Go 博客后端服务
    build: . # 构建当前目录下的 Dockerfile
    restart: unless-stopped # 容器异常退出时自动重启
    extra_hosts:
      - "host.docker.internal:host-gateway" # 允许容器内访问宿主机
    ports:
      - "8080:8080" # 映射宿主机 8080 端口到容器
    volumes:
      - blog-backend-go-dev:/blog-backend-go-dev # 挂载开发目录
    networks:
      - bridge # 加入默认 bridge 网络，与 mongodb 容器互通(两者网络要一致)

volumes:
  blog-backend-go-dev: # Go 项目开发目录卷
    external: true # 指定该卷已存在并且是在 Compose 外部创建的.