version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - /app/.env
    ports:
      - "8080:8080"
    volumes:
      - /home/env/.env.blog-backend-go.dev:/app/.env
